FROM ubuntu:14.04

LABEL maintainer="William Irons <wdirons@us.ibm.com>"

# Copy and run the install scripts.
COPY install/*.sh /install/
RUN /install/install_bootstrap_deb_packages.sh
RUN add-apt-repository -y ppa:openjdk-r/ppa
RUN /install/install_deb_packages.sh
RUN /install/install_openblas_ppc64le.sh
RUN /install/install_python2.7_pip_packages.sh
RUN /install/install_python3.5_pip_packages.sh
RUN /install/install_python3.6_pip_packages.sh
RUN /install/install_python3.7_pip_packages.sh
RUN /install/install_bazel_from_source.sh

# Set up the master bazelrc configuration file.
COPY install/.bazelrc /etc/bazel.bazelrc

#From https://github.com/jenkinsci/docker-ssh-slave/blob/master/Dockerfile
ARG user=jenkins
ARG group=jenkins
ARG uid=10000
ARG gid=10000
ARG JENKINS_AGENT_HOME=/home/${user}

ENV JENKINS_AGENT_HOME ${JENKINS_AGENT_HOME}

RUN groupadd -g ${gid} ${group} \
&& useradd -d "${JENKINS_AGENT_HOME}" -u "${uid}" -g "${gid}" -m -s /bin/bash "${user}" \
&& echo "jenkins ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

VOLUME "${JENKINS_AGENT_HOME}" "/tmp" "/run" "/var/run"
WORKDIR "${JENKINS_AGENT_HOME}"
